services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "StudentMgmt!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"                        # Optional: Specify SQL Server edition (Express, Developer), default "Developer"
    volumes:
      - student-mgmt:/var/opt/mssql
    networks:
      - mssql-network

volumes:
  student-mgmt:

networks:
  mssql-network:
    driver: bridge

# Create the database after container creation:
# docker exec -it /var/mssql-tools18/bin/sqlcmd -S localhost,1433 -U sa -P "Password!Here"
#  CREATE DATABASE student_mgmt;
#  GO;